# Generated by Django 6.0.1 on 2026-01-09 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_artista_instagram_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista'),
        ),
    ]
