# Generated by Django 6.0.1 on 2026-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_artista_bio_remove_trabalho_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='imagem',
            field=models.ImageField(default=None, upload_to='trabalhos/'),
            preserve_default=False,
        ),
    ]
