# Generated by Django 6.0.1 on 2026-01-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trabalho_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='trabalhos/'),
        ),
    ]
