# Generated by Django 6.0.1 on 2026-01-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estilo_trabalho_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estilo'),
        ),
    ]
