# Generated by Django 6.0.1 on 2026-01-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trabalho_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estilo'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='imagem',
            field=models.ImageField(default=None, upload_to='trabalhos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
