# Generated by Django 6.0.1 on 2026-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estilo_ativo_alter_trabalho_estilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
