# Generated by Django 6.0.1 on 2026-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria_cliente_pedido_pagamento_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
