# Generated by Django 6.0.1 on 2026-02-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_atual',
            new_name='preco',
        ),
    ]
