# Generated by Django 6.0.1 on 2026-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_preco_atual_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('CRIADO', 'Criado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('ENVIADO', 'Enviado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CRIADO', max_length=30),
        ),
    ]
